/* Writes j6/sets.mjs from the J-6 Owner's Manual's Chord Set List page. (D-088)

     node tools/j6-import.mjs <saved Chord Set List page.html>

   The page is https://static.roland.com/manuals/J-6_manual_v102/eng/28645807.html,
   saved from a browser. Its one table has two rows per set: the number, the
   genre and twelve labels, then the twelve voicings, high to low, written
   without spaces ("E4D4G3C3"). Both are kept exactly as printed. Errors in
   the manual are recorded in DESIGN.md (D-082) and caught by the validator;
   they are never corrected here. */
import { readFileSync, writeFileSync } from "node:fs";

const html = readFileSync(process.argv[2], "utf8");
const table = html.slice(html.indexOf('<table class="confluenceTable"'), html.indexOf("</table>"));
const text = (cell) => cell.replace(/<br\s*\/?>/g, " ").replace(/<[^>]+>/g, "").replace(/&nbsp;/g, " ").replace(/&amp;/g, "&").replace(/\s+/g, " ").trim();
const rows = [...table.matchAll(/<tr>([\s\S]*?)<\/tr>/g)]
  .map((r) => [...r[1].matchAll(/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/g)].map((c) => text(c[1])))
  .filter((r) => /^\d+$/.test(r[0]) || /^([A-G](#|b)?-?\d\s*)*$/.test(r.join("")));

const sets = {};
for (let i = 0; i < rows.length; i++) {
  const [no, genre, ...labels] = rows[i];
  if (!/^\d+$/.test(no)) continue;
  const voicings = rows[i + 1];
  if (labels.length !== 12 || voicings.length !== 12) throw new Error(`set ${no}: ${labels.length} labels, ${voicings.length} voicings`);
  const notes = voicings.map((v) => {
    const found = v.replace(/\s+/g, "").match(/[A-G](?:#|b)?-?\d/g) ?? [];
    if (found.join("") !== v.replace(/\s+/g, "")) throw new Error(`set ${no}: can't read the voicing "${v}"`);
    return found.join(" ");
  });
  sets[no] = { genre, keys: labels.map((l, k) => [l, notes[k]]) };
  i++;
}
const n = Object.keys(sets).length;
if (n !== 100) throw new Error(`expected 100 sets, found ${n}`);

const body = Object.entries(sets).map(([no, s]) =>
  `  ${no}: { genre: ${JSON.stringify(s.genre)}, keys: [\n` +
  s.keys.map(([l, v]) => `    [${JSON.stringify(l)}, ${JSON.stringify(v)}],`).join("\n") + "\n  ] },").join("\n");
writeFileSync(new URL("../j6/sets.mjs", import.meta.url), `/* The J-6's 100 chord sets, exactly as printed in the Roland J-6 Owner's Manual
   v1.02, Chord Set List:
   https://static.roland.com/manuals/J-6_manual_v102/eng/28645807.html

   Generated by tools/j6-import.mjs. Do not edit by hand. Each key is
   [label, voicing high → low]. Errors in the manual stay as printed: the
   validator flags them and DESIGN.md (D-082) lists them. Sets 14 to 16 are
   interval stacks and have no labels. (D-088) */
export const SETS = {
${body}
};
`);
console.log(`j6/sets.mjs: ${n} sets, ${n * 12} keys`);
