/* Turns the single-file app into a small website that installs like an app:
   a home-screen icon, full screen, working offline, and updating itself when
   a new version is uploaded. (D-076, UC-31)

     node tools/package-site.mjs <app.html> <icon-dir> <out-dir> [sketchpad|j6]

   Two apps share the site: Sketchpad at the root and the J-6 Explorer in
   j6/. Each is its own installable app, with its own name, icon, manifest and
   offline cache, and neither app's update touches the other's cache. (D-087)

   Everything here is a pure function of its inputs except the CLI at the
   bottom, so the tests can check the site without a browser. */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

export const SITES = {
  sketchpad: { name: "Sketchpad", shortName: "Sketchpad", cachePrefix: "sketchpad-",
    description: "Pick a key, play chords, practise lessons on the piano." },
  j6: { name: "J-6 Explorer", shortName: "J-6", cachePrefix: "j6-explorer-",
    description: "What the Roland J-6 is playing, and how to play a progression on it." },
};
export const SITE_NAME = SITES.sketchpad.name;
export const BACKGROUND = "#EDE7DA";
export const CACHE_PREFIX = SITES.sketchpad.cachePrefix;
export const ICON_SIZES = [180, 192, 512];
export const iconName = (size) => `icon-${size}.png`;

/* The app as an installable thing: its name, its icon, and that it opens
   full screen at its own folder rather than wherever it was found. */
export function manifest(site = SITES.sketchpad) {
  return JSON.stringify({
    name: site.name,
    short_name: site.shortName,
    description: site.description,
    start_url: "./",
    scope: "./",
    display: "standalone",
    orientation: "any",
    background_color: BACKGROUND,
    theme_color: BACKGROUND,
    icons: ICON_SIZES.filter((s) => s !== 180).map((s) => ({ src: iconName(s), sizes: `${s}x${s}`, type: "image/png", purpose: "any" })),
  }, null, 2) + "\n";
}

/* iOS reads its own tags, not the manifest, for the home-screen icon and
   for opening without Safari's bars. */
export function headTags(site = SITES.sketchpad) {
  return [
    `<link rel="manifest" href="manifest.webmanifest">`,
    `<meta name="theme-color" content="${BACKGROUND}">`,
    `<meta name="apple-mobile-web-app-capable" content="yes">`,
    `<meta name="mobile-web-app-capable" content="yes">`,
    `<meta name="apple-mobile-web-app-title" content="${site.name}">`,
    `<meta name="apple-mobile-web-app-status-bar-style" content="default">`,
    `<link rel="apple-touch-icon" href="${iconName(180)}">`,
  ].join("");
}

/* Registration never throws into the app: if the browser refuses, the app
   still works online exactly as before. */
export const REGISTER = `<script>if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));</script>`;

export function installable(html, site = SITES.sketchpad) {
  if (!html.includes("</head>")) throw new Error("the page has no </head> to add the install tags to");
  if (!html.includes("</body>")) throw new Error("the page has no </body> to add the registration to");
  const i = html.indexOf("</head>");
  const withHead = html.slice(0, i) + headTags(site) + html.slice(i);
  const j = withHead.lastIndexOf("</body>");
  return withHead.slice(0, j) + REGISTER + withHead.slice(j);
}

/* The version is a fingerprint of everything the site ships, so any change
   to any file makes a new cache, and an unchanged upload keeps the old one. */
export function contentVersion(files) {
  const h = createHash("sha256");
  for (const name of Object.keys(files).sort()) { h.update(name); h.update("\0"); h.update(files[name]); h.update("\0"); }
  return h.digest("hex").slice(0, 12);
}

/* Cache first, from a cache named after the version. A new upload means a new
   sw.js, which the browser notices on the next open; it fetches the new files
   past any HTTP cache, switches over, and deletes the old cache. The page
   already open keeps running on what it loaded. */
export function serviceWorker(fileNames, version, site = SITES.sketchpad) {
  const CACHE_PREFIX = site.cachePrefix;   // each app's caches carry its own prefix (D-087)
  const files = ["./", ...fileNames.map((f) => "./" + f)];
  return `/* ${site.name} offline cache, generated by tools/package-site.mjs (D-076) */
const VERSION = ${JSON.stringify(CACHE_PREFIX + version)};
const FILES = ${JSON.stringify(files)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(VERSION)
      .then((cache) => cache.addAll(FILES.map((f) => new Request(f, { cache: "reload" }))))
      .then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys
        .filter((k) => k.startsWith(${JSON.stringify(CACHE_PREFIX)}) && k !== VERSION)
        .map((k) => caches.delete(k))))
      .then(() => self.clients.claim()));
});

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;
  event.respondWith(
    caches.open(VERSION)
      .then((cache) => cache.match(event.request, { ignoreSearch: true }))
      .then((hit) => hit || fetch(event.request)));
});
`;
}

/* The whole site as { file name: contents }. */
export function packageSite(appHtml, icons, site = SITES.sketchpad) {
  const files = { "index.html": installable(appHtml, site), "manifest.webmanifest": manifest(site) };
  for (const size of ICON_SIZES) {
    const icon = icons[iconName(size)];
    if (!icon) throw new Error(`missing ${iconName(size)}`);
    files[iconName(size)] = icon;
  }
  const version = contentVersion(files);
  files["sw.js"] = serviceWorker(Object.keys(files).sort(), version, site);
  return { files, version };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const [appPath, iconDir, outDir, which = "sketchpad"] = process.argv.slice(2);
  if (!outDir || !SITES[which]) { console.error("usage: node tools/package-site.mjs <app.html> <icon-dir> <out-dir> [sketchpad|j6]"); process.exit(1); }
  const icons = Object.fromEntries(readdirSync(iconDir).filter((f) => f.endsWith(".png")).map((f) => [f, readFileSync(join(iconDir, f))]));
  const { files, version } = packageSite(readFileSync(appPath, "utf8"), icons, SITES[which]);
  mkdirSync(outDir, { recursive: true });
  for (const [name, body] of Object.entries(files)) writeFileSync(join(outDir, name), body);
  console.log(`${SITES[which].name} site version ${version}: ${Object.keys(files).sort().join(", ")}`);
}
